### ISSUE TITLE
dumping this here before I delete my fork

### ISSUE THREAD

**Issue by tanho63** [jdtrat/ds4psych_actions#3]
```
on:
  workflow_dispatch:

name: runmyR

jobs:
  runmyR:
    runs-on: macOS-latest
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Do things in R
        run: |
          list.files()
          cat("Hullo")
          cat("\n")
          source("R/grading_script.R")
        shell: Rscript {0}
```
